//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDevTools.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDevTools.Site.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyDevTools.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy-first developer tools, where all data stays in your browser.
        /// </summary>
        public static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Common_Input {
            get {
                return ResourceManager.GetString("Common_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Common_Output {
            get {
                return ResourceManager.GetString("Common_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string HashCalculator_Calculate {
            get {
                return ResourceManager.GetString("HashCalculator_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HashCalculator_Clear {
            get {
                return ResourceManager.GetString("HashCalculator_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HashCalculator_Cancel {
            get {
                return ResourceManager.GetString("HashCalculator_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string HashCalculator_Copied {
            get {
                return ResourceManager.GetString("HashCalculator_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        public static string HashCalculator_AlgorithmsTitle {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string HashCalculator_AlgorithmsSelected {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string HashCalculator_AlgorithmsAvailable {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search algorithms....
        /// </summary>
        public static string HashCalculator_AlgorithmsSearchPlaceholder {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsSearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string HashCalculator_AlgorithmsReset {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select at least one algorithm..
        /// </summary>
        public static string HashCalculator_SelectAtLeastOneAlgorithm {
            get {
                return ResourceManager.GetString("HashCalculator_SelectAtLeastOneAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string HashCalculator_Copy {
            get {
                return ResourceManager.GetString("HashCalculator_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate MD5, SHA-1, SHA-256, SHA-512 hashes from text or files.
        /// </summary>
        public static string HashCalculator_Description {
            get {
                return ResourceManager.GetString("HashCalculator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string HashCalculator_InputLabel {
            get {
                return ResourceManager.GetString("HashCalculator_InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to hash....
        /// </summary>
        public static string HashCalculator_InputPlaceholder {
            get {
                return ResourceManager.GetString("HashCalculator_InputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File (optional).
        /// </summary>
        public static string HashCalculator_FileLabel {
            get {
                return ResourceManager.GetString("HashCalculator_FileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, the text input is ignored..
        /// </summary>
        public static string HashCalculator_FileHint {
            get {
                return ResourceManager.GetString("HashCalculator_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hashing file....
        /// </summary>
        public static string HashCalculator_FileProgressTitle {
            get {
                return ResourceManager.GetString("HashCalculator_FileProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Calculator.
        /// </summary>
        public static string HashCalculator_Title {
            get {
                return ResourceManager.GetString("HashCalculator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is sent to the server.
        /// </summary>
        public static string Home_NoDataSent {
            get {
                return ResourceManager.GetString("Home_NoDataSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose What You Need.
        /// </summary>
        public static string Home_FeatureAlgorithmsTitle {
            get {
                return ResourceManager.GetString("Home_FeatureAlgorithmsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the algorithms you want and save your set in the browser..
        /// </summary>
        public static string Home_FeatureAlgorithmsDescription {
            get {
                return ResourceManager.GetString("Home_FeatureAlgorithmsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multilingual.
        /// </summary>
        public static string Home_FeatureLanguagesTitle {
            get {
                return ResourceManager.GetString("Home_FeatureLanguagesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available in multiple languages for developers worldwide..
        /// </summary>
        public static string Home_FeatureLanguagesDescription {
            get {
                return ResourceManager.GetString("Home_FeatureLanguagesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy First.
        /// </summary>
        public static string Home_FeaturePrivacyTitle {
            get {
                return ResourceManager.GetString("Home_FeaturePrivacyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All processing happens in your browser. Zero data sent to servers..
        /// </summary>
        public static string Home_FeaturePrivacyDescription {
            get {
                return ResourceManager.GetString("Home_FeaturePrivacyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; Efficient.
        /// </summary>
        public static string Home_FeatureWasmTitle {
            get {
                return ResourceManager.GetString("Home_FeatureWasmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Powered by WebAssembly for native-like performance..
        /// </summary>
        public static string Home_FeatureWasmDescription {
            get {
                return ResourceManager.GetString("Home_FeatureWasmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy-first tools for developers. All processing happens in your browser..
        /// </summary>
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Nav_Tools {
            get {
                return ResourceManager.GetString("Nav_Tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL Encoder.
        /// </summary>
        public static string Nav_UrlEncoder {
            get {
                return ResourceManager.GetString("Nav_UrlEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string Theme_Toggle {
            get {
                return ResourceManager.GetString("Theme_Toggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string UrlEncoder_ActionEncode {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string UrlEncoder_ActionClear {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string UrlEncoder_ActionDecode {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string UrlEncoder_ActionSwap {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string UrlEncoder_CharsetLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string UrlEncoder_Copied {
            get {
                return ResourceManager.GetString("UrlEncoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string UrlEncoder_Copy {
            get {
                return ResourceManager.GetString("UrlEncoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode URL-encoded text (percent-encoding) with selectable modes and charsets — all in your browser.
        /// </summary>
        public static string UrlEncoder_Description {
            get {
                return ResourceManager.GetString("UrlEncoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string UrlEncoder_InputLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_InputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text or URL-encoded string....
        /// </summary>
        public static string UrlEncoder_InputPlaceholder {
            get {
                return ResourceManager.GetString("UrlEncoder_InputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string UrlEncoder_LinkBase32 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string UrlEncoder_LinkBase58 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase58", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string UrlEncoder_LinkBase64 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string UrlEncoder_LinkHex {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string UrlEncoder_ModeLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_ModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Component (encodeURIComponent-like).
        /// </summary>
        public static string UrlEncoder_Mode_Component {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Component", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Form (application/x-www-form-urlencoded).
        /// </summary>
        public static string UrlEncoder_Mode_Form {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URI (encodeURI-like).
        /// </summary>
        public static string UrlEncoder_Mode_Uri {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Uri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string UrlEncoder_OtherFormats {
            get {
                return ResourceManager.GetString("UrlEncoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string UrlEncoder_OutputLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL Encoder / Decoder.
        /// </summary>
        public static string UrlEncoder_Title {
            get {
                return ResourceManager.GetString("UrlEncoder_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Nav_HexEncoder {
            get {
                return ResourceManager.GetString("Nav_HexEncoder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex Encoder / Decoder.
        /// </summary>
        public static string HexEncoder_Title {
            get {
                return ResourceManager.GetString("HexEncoder_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode Hex for text and files — all in your browser.
        /// </summary>
        public static string HexEncoder_Description {
            get {
                return ResourceManager.GetString("HexEncoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string HexEncoder_OtherFormats {
            get {
                return ResourceManager.GetString("HexEncoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string HexEncoder_LinkUrl {
            get {
                return ResourceManager.GetString("HexEncoder_LinkUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string HexEncoder_LinkBase32 {
            get {
                return ResourceManager.GetString("HexEncoder_LinkBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string HexEncoder_LinkBase58 {
            get {
                return ResourceManager.GetString("HexEncoder_LinkBase58", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string HexEncoder_LinkBase64 {
            get {
                return ResourceManager.GetString("HexEncoder_LinkBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input (text).
        /// </summary>
        public static string HexEncoder_InputTextLabel {
            get {
                return ResourceManager.GetString("HexEncoder_InputTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text....
        /// </summary>
        public static string HexEncoder_InputTextPlaceholder {
            get {
                return ResourceManager.GetString("HexEncoder_InputTextPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        public static string HexEncoder_InputFileLabel {
            get {
                return ResourceManager.GetString("HexEncoder_InputFileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, it will be used instead of the text input.
        /// </summary>
        public static string HexEncoder_FileHint {
            get {
                return ResourceManager.GetString("HexEncoder_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string HexEncoder_CharsetLabel {
            get {
                return ResourceManager.GetString("HexEncoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex case.
        /// </summary>
        public static string HexEncoder_CaseLabel {
            get {
                return ResourceManager.GetString("HexEncoder_CaseLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to lower (a-f).
        /// </summary>
        public static string HexEncoder_CaseLower {
            get {
                return ResourceManager.GetString("HexEncoder_CaseLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UPPER (A-F).
        /// </summary>
        public static string HexEncoder_CaseUpper {
            get {
                return ResourceManager.GetString("HexEncoder_CaseUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode options.
        /// </summary>
        public static string HexEncoder_DecodeOptionsLabel {
            get {
                return ResourceManager.GetString("HexEncoder_DecodeOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ignore whitespace.
        /// </summary>
        public static string HexEncoder_IgnoreWhitespace {
            get {
                return ResourceManager.GetString("HexEncoder_IgnoreWhitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow separators (e.g. ':' and '-').
        /// </summary>
        public static string HexEncoder_AllowSeparators {
            get {
                return ResourceManager.GetString("HexEncoder_AllowSeparators", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow 0x prefix.
        /// </summary>
        public static string HexEncoder_Allow0x {
            get {
                return ResourceManager.GetString("HexEncoder_Allow0x", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output mode.
        /// </summary>
        public static string HexEncoder_OutputModeLabel {
            get {
                return ResourceManager.GetString("HexEncoder_OutputModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string HexEncoder_OutputModePreview {
            get {
                return ResourceManager.GetString("HexEncoder_OutputModePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string HexEncoder_OutputModeFull {
            get {
                return ResourceManager.GetString("HexEncoder_OutputModeFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string HexEncoder_ActionEncode {
            get {
                return ResourceManager.GetString("HexEncoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string HexEncoder_ActionDecode {
            get {
                return ResourceManager.GetString("HexEncoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string HexEncoder_ActionSwap {
            get {
                return ResourceManager.GetString("HexEncoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HexEncoder_ActionClear {
            get {
                return ResourceManager.GetString("HexEncoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string HexEncoder_OutputLabel {
            get {
                return ResourceManager.GetString("HexEncoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string HexEncoder_Copy {
            get {
                return ResourceManager.GetString("HexEncoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string HexEncoder_Copied {
            get {
                return ResourceManager.GetString("HexEncoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string HexEncoder_Download {
            get {
                return ResourceManager.GetString("HexEncoder_Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing file.
        /// </summary>
        public static string HexEncoder_FileProgressTitle {
            get {
                return ResourceManager.GetString("HexEncoder_FileProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HexEncoder_Cancel {
            get {
                return ResourceManager.GetString("HexEncoder_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string Nav_Base64Encoder {
            get {
                return ResourceManager.GetString("Nav_Base64Encoder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64 Encoder / Decoder.
        /// </summary>
        public static string Base64Encoder_Title {
            get {
                return ResourceManager.GetString("Base64Encoder_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode Base64 for text and files — all in your browser.
        /// </summary>
        public static string Base64Encoder_Description {
            get {
                return ResourceManager.GetString("Base64Encoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string Base64Encoder_OtherFormats {
            get {
                return ResourceManager.GetString("Base64Encoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Base64Encoder_LinkHex {
            get {
                return ResourceManager.GetString("Base64Encoder_LinkHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string Base64Encoder_LinkBase32 {
            get {
                return ResourceManager.GetString("Base64Encoder_LinkBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string Base64Encoder_LinkBase58 {
            get {
                return ResourceManager.GetString("Base64Encoder_LinkBase58", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Base64Encoder_LinkUrl {
            get {
                return ResourceManager.GetString("Base64Encoder_LinkUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input (text).
        /// </summary>
        public static string Base64Encoder_InputTextLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_InputTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text or Base64....
        /// </summary>
        public static string Base64Encoder_InputTextPlaceholder {
            get {
                return ResourceManager.GetString("Base64Encoder_InputTextPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        public static string Base64Encoder_InputFileLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_InputFileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, it will be used instead of the text input..
        /// </summary>
        public static string Base64Encoder_FileHint {
            get {
                return ResourceManager.GetString("Base64Encoder_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string Base64Encoder_CharsetLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        public static string Base64Encoder_AlphabetLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_AlphabetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard (+/).
        /// </summary>
        public static string Base64Encoder_AlphabetStandard {
            get {
                return ResourceManager.GetString("Base64Encoder_AlphabetStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL-safe (-_).
        /// </summary>
        public static string Base64Encoder_AlphabetUrlSafe {
            get {
                return ResourceManager.GetString("Base64Encoder_AlphabetUrlSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string Base64Encoder_PaddingLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_PaddingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Base64Encoder_PaddingRequired {
            get {
                return ResourceManager.GetString("Base64Encoder_PaddingRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Base64Encoder_PaddingOptional {
            get {
                return ResourceManager.GetString("Base64Encoder_PaddingOptional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No padding.
        /// </summary>
        public static string Base64Encoder_PaddingNone {
            get {
                return ResourceManager.GetString("Base64Encoder_PaddingNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line wrap.
        /// </summary>
        public static string Base64Encoder_LineWrapLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_LineWrapLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Base64Encoder_LineWrapNone {
            get {
                return ResourceManager.GetString("Base64Encoder_LineWrapNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 76 chars.
        /// </summary>
        public static string Base64Encoder_LineWrap76 {
            get {
                return ResourceManager.GetString("Base64Encoder_LineWrap76", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode options.
        /// </summary>
        public static string Base64Encoder_DecodeOptionsLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_DecodeOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow whitespace/newlines.
        /// </summary>
        public static string Base64Encoder_AllowWhitespace {
            get {
                return ResourceManager.GetString("Base64Encoder_AllowWhitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File output.
        /// </summary>
        public static string Base64Encoder_OutputModeLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_OutputModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview in output (download full).
        /// </summary>
        public static string Base64Encoder_OutputModePreview {
            get {
                return ResourceManager.GetString("Base64Encoder_OutputModePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Render full output (may be slow).
        /// </summary>
        public static string Base64Encoder_OutputModeFull {
            get {
                return ResourceManager.GetString("Base64Encoder_OutputModeFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Base64Encoder_ActionEncode {
            get {
                return ResourceManager.GetString("Base64Encoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Base64Encoder_ActionDecode {
            get {
                return ResourceManager.GetString("Base64Encoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Base64Encoder_ActionSwap {
            get {
                return ResourceManager.GetString("Base64Encoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Base64Encoder_ActionClear {
            get {
                return ResourceManager.GetString("Base64Encoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Base64Encoder_OutputLabel {
            get {
                return ResourceManager.GetString("Base64Encoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Base64Encoder_Copy {
            get {
                return ResourceManager.GetString("Base64Encoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Base64Encoder_Copied {
            get {
                return ResourceManager.GetString("Base64Encoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Base64Encoder_Download {
            get {
                return ResourceManager.GetString("Base64Encoder_Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing file....
        /// </summary>
        public static string Base64Encoder_FileProgressTitle {
            get {
                return ResourceManager.GetString("Base64Encoder_FileProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Base64Encoder_Cancel {
            get {
                return ResourceManager.GetString("Base64Encoder_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string Nav_Base32Encoder {
            get {
                return ResourceManager.GetString("Nav_Base32Encoder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32 Encoder / Decoder.
        /// </summary>
        public static string Base32Encoder_Title {
            get {
                return ResourceManager.GetString("Base32Encoder_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode Base32 for text and files — all in your browser.
        /// </summary>
        public static string Base32Encoder_Description {
            get {
                return ResourceManager.GetString("Base32Encoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string Base32Encoder_OtherFormats {
            get {
                return ResourceManager.GetString("Base32Encoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Base32Encoder_LinkHex {
            get {
                return ResourceManager.GetString("Base32Encoder_LinkHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string Base32Encoder_LinkBase64 {
            get {
                return ResourceManager.GetString("Base32Encoder_LinkBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string Base32Encoder_LinkBase58 {
            get {
                return ResourceManager.GetString("Base32Encoder_LinkBase58", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Base32Encoder_LinkUrl {
            get {
                return ResourceManager.GetString("Base32Encoder_LinkUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input (text).
        /// </summary>
        public static string Base32Encoder_InputTextLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_InputTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text or Base32....
        /// </summary>
        public static string Base32Encoder_InputTextPlaceholder {
            get {
                return ResourceManager.GetString("Base32Encoder_InputTextPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        public static string Base32Encoder_InputFileLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_InputFileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, it will be used instead of the text input..
        /// </summary>
        public static string Base32Encoder_FileHint {
            get {
                return ResourceManager.GetString("Base32Encoder_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string Base32Encoder_CharsetLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        public static string Base32Encoder_AlphabetLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_AlphabetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RFC 4648 (A-Z2-7).
        /// </summary>
        public static string Base32Encoder_AlphabetRfc4648 {
            get {
                return ResourceManager.GetString("Base32Encoder_AlphabetRfc4648", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crockford (0-9A-Z).
        /// </summary>
        public static string Base32Encoder_AlphabetCrockford {
            get {
                return ResourceManager.GetString("Base32Encoder_AlphabetCrockford", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to z-base-32.
        /// </summary>
        public static string Base32Encoder_AlphabetZBase32 {
            get {
                return ResourceManager.GetString("Base32Encoder_AlphabetZBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string Base32Encoder_PaddingLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_PaddingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Base32Encoder_PaddingRequired {
            get {
                return ResourceManager.GetString("Base32Encoder_PaddingRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Base32Encoder_PaddingOptional {
            get {
                return ResourceManager.GetString("Base32Encoder_PaddingOptional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No padding.
        /// </summary>
        public static string Base32Encoder_PaddingNone {
            get {
                return ResourceManager.GetString("Base32Encoder_PaddingNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Letter case.
        /// </summary>
        public static string Base32Encoder_CaseLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_CaseLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Base32Encoder_CaseAuto {
            get {
                return ResourceManager.GetString("Base32Encoder_CaseAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string Base32Encoder_CaseUpper {
            get {
                return ResourceManager.GetString("Base32Encoder_CaseUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string Base32Encoder_CaseLower {
            get {
                return ResourceManager.GetString("Base32Encoder_CaseLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode options.
        /// </summary>
        public static string Base32Encoder_DecodeOptionsLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_DecodeOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow whitespace/newlines.
        /// </summary>
        public static string Base32Encoder_AllowWhitespace {
            get {
                return ResourceManager.GetString("Base32Encoder_AllowWhitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File output.
        /// </summary>
        public static string Base32Encoder_OutputModeLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_OutputModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview in output (download full).
        /// </summary>
        public static string Base32Encoder_OutputModePreview {
            get {
                return ResourceManager.GetString("Base32Encoder_OutputModePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Render full output (may be slow).
        /// </summary>
        public static string Base32Encoder_OutputModeFull {
            get {
                return ResourceManager.GetString("Base32Encoder_OutputModeFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Base32Encoder_ActionEncode {
            get {
                return ResourceManager.GetString("Base32Encoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Base32Encoder_ActionDecode {
            get {
                return ResourceManager.GetString("Base32Encoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Base32Encoder_ActionSwap {
            get {
                return ResourceManager.GetString("Base32Encoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Base32Encoder_ActionClear {
            get {
                return ResourceManager.GetString("Base32Encoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Base32Encoder_OutputLabel {
            get {
                return ResourceManager.GetString("Base32Encoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Base32Encoder_Copy {
            get {
                return ResourceManager.GetString("Base32Encoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Base32Encoder_Copied {
            get {
                return ResourceManager.GetString("Base32Encoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Base32Encoder_Download {
            get {
                return ResourceManager.GetString("Base32Encoder_Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing file....
        /// </summary>
        public static string Base32Encoder_FileProgressTitle {
            get {
                return ResourceManager.GetString("Base32Encoder_FileProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Base32Encoder_Cancel {
            get {
                return ResourceManager.GetString("Base32Encoder_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string Nav_Base58Encoder {
            get {
                return ResourceManager.GetString("Nav_Base58Encoder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58 Encoder / Decoder.
        /// </summary>
        public static string Base58Encoder_Title {
            get {
                return ResourceManager.GetString("Base58Encoder_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode Base58 for text and files — all in your browser.
        /// </summary>
        public static string Base58Encoder_Description {
            get {
                return ResourceManager.GetString("Base58Encoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string Base58Encoder_OtherFormats {
            get {
                return ResourceManager.GetString("Base58Encoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Base58Encoder_LinkHex {
            get {
                return ResourceManager.GetString("Base58Encoder_LinkHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string Base58Encoder_LinkBase32 {
            get {
                return ResourceManager.GetString("Base58Encoder_LinkBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string Base58Encoder_LinkBase64 {
            get {
                return ResourceManager.GetString("Base58Encoder_LinkBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Base58Encoder_LinkUrl {
            get {
                return ResourceManager.GetString("Base58Encoder_LinkUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input (text).
        /// </summary>
        public static string Base58Encoder_InputTextLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_InputTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text or Base58....
        /// </summary>
        public static string Base58Encoder_InputTextPlaceholder {
            get {
                return ResourceManager.GetString("Base58Encoder_InputTextPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        public static string Base58Encoder_InputFileLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_InputFileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, it will be used instead of the text input..
        /// </summary>
        public static string Base58Encoder_FileHint {
            get {
                return ResourceManager.GetString("Base58Encoder_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string Base58Encoder_CharsetLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        public static string Base58Encoder_AlphabetLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_AlphabetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bitcoin (Base58).
        /// </summary>
        public static string Base58Encoder_AlphabetBitcoin {
            get {
                return ResourceManager.GetString("Base58Encoder_AlphabetBitcoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Flickr.
        /// </summary>
        public static string Base58Encoder_AlphabetFlickr {
            get {
                return ResourceManager.GetString("Base58Encoder_AlphabetFlickr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ripple.
        /// </summary>
        public static string Base58Encoder_AlphabetRipple {
            get {
                return ResourceManager.GetString("Base58Encoder_AlphabetRipple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode options.
        /// </summary>
        public static string Base58Encoder_DecodeOptionsLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_DecodeOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow whitespace/newlines.
        /// </summary>
        public static string Base58Encoder_AllowWhitespace {
            get {
                return ResourceManager.GetString("Base58Encoder_AllowWhitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File output.
        /// </summary>
        public static string Base58Encoder_OutputModeLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_OutputModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview in output (download full).
        /// </summary>
        public static string Base58Encoder_OutputModePreview {
            get {
                return ResourceManager.GetString("Base58Encoder_OutputModePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Render full output (may be slow).
        /// </summary>
        public static string Base58Encoder_OutputModeFull {
            get {
                return ResourceManager.GetString("Base58Encoder_OutputModeFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Base58Encoder_ActionEncode {
            get {
                return ResourceManager.GetString("Base58Encoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Base58Encoder_ActionDecode {
            get {
                return ResourceManager.GetString("Base58Encoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Base58Encoder_ActionSwap {
            get {
                return ResourceManager.GetString("Base58Encoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Base58Encoder_ActionClear {
            get {
                return ResourceManager.GetString("Base58Encoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Base58Encoder_OutputLabel {
            get {
                return ResourceManager.GetString("Base58Encoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Base58Encoder_Copy {
            get {
                return ResourceManager.GetString("Base58Encoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Base58Encoder_Copied {
            get {
                return ResourceManager.GetString("Base58Encoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Base58Encoder_Download {
            get {
                return ResourceManager.GetString("Base58Encoder_Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing file....
        /// </summary>
        public static string Base58Encoder_FileProgressTitle {
            get {
                return ResourceManager.GetString("Base58Encoder_FileProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Base58Encoder_Cancel {
            get {
                return ResourceManager.GetString("Base58Encoder_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58 encoding is limited to {0} due to algorithmic complexity. Your file is {1}. Please use Base64 or Hex encoding for larger files.
        /// </summary>
        public static string Base58Encoder_FileSizeLimitEncode {
            get {
                return ResourceManager.GetString("Base58Encoder_FileSizeLimitEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58 decoding is limited to {0} due to algorithmic complexity. Your file is {1}. Please use Base64 or Hex encoding for larger files.
        /// </summary>
        public static string Base58Encoder_FileSizeLimitDecode {
            get {
                return ResourceManager.GetString("Base58Encoder_FileSizeLimitDecode", resourceCulture);
            }
        }
    }
}
