//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDevTools.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDevTools.Site.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyDevTools.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy-first developer tools, where all data stays in your browser.
        /// </summary>
        public static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Common_Input {
            get {
                return ResourceManager.GetString("Common_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Common_Output {
            get {
                return ResourceManager.GetString("Common_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string HashCalculator_Calculate {
            get {
                return ResourceManager.GetString("HashCalculator_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HashCalculator_Clear {
            get {
                return ResourceManager.GetString("HashCalculator_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HashCalculator_Cancel {
            get {
                return ResourceManager.GetString("HashCalculator_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string HashCalculator_Copied {
            get {
                return ResourceManager.GetString("HashCalculator_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        public static string HashCalculator_AlgorithmsTitle {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string HashCalculator_AlgorithmsSelected {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string HashCalculator_AlgorithmsAvailable {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search algorithms....
        /// </summary>
        public static string HashCalculator_AlgorithmsSearchPlaceholder {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsSearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string HashCalculator_AlgorithmsReset {
            get {
                return ResourceManager.GetString("HashCalculator_AlgorithmsReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select at least one algorithm..
        /// </summary>
        public static string HashCalculator_SelectAtLeastOneAlgorithm {
            get {
                return ResourceManager.GetString("HashCalculator_SelectAtLeastOneAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string HashCalculator_Copy {
            get {
                return ResourceManager.GetString("HashCalculator_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate MD5, SHA-1, SHA-256, SHA-512 hashes from text or files.
        /// </summary>
        public static string HashCalculator_Description {
            get {
                return ResourceManager.GetString("HashCalculator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string HashCalculator_InputLabel {
            get {
                return ResourceManager.GetString("HashCalculator_InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to hash....
        /// </summary>
        public static string HashCalculator_InputPlaceholder {
            get {
                return ResourceManager.GetString("HashCalculator_InputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File (optional).
        /// </summary>
        public static string HashCalculator_FileLabel {
            get {
                return ResourceManager.GetString("HashCalculator_FileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a file is selected, the text input is ignored..
        /// </summary>
        public static string HashCalculator_FileHint {
            get {
                return ResourceManager.GetString("HashCalculator_FileHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hashing file....
        /// </summary>
        public static string HashCalculator_FileProgressTitle {
            get {
                return ResourceManager.GetString("HashCalculator_FileProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Calculator.
        /// </summary>
        public static string HashCalculator_Title {
            get {
                return ResourceManager.GetString("HashCalculator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is sent to the server.
        /// </summary>
        public static string Home_NoDataSent {
            get {
                return ResourceManager.GetString("Home_NoDataSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose What You Need.
        /// </summary>
        public static string Home_FeatureAlgorithmsTitle {
            get {
                return ResourceManager.GetString("Home_FeatureAlgorithmsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the algorithms you want and save your set in the browser..
        /// </summary>
        public static string Home_FeatureAlgorithmsDescription {
            get {
                return ResourceManager.GetString("Home_FeatureAlgorithmsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multilingual.
        /// </summary>
        public static string Home_FeatureLanguagesTitle {
            get {
                return ResourceManager.GetString("Home_FeatureLanguagesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available in multiple languages for developers worldwide..
        /// </summary>
        public static string Home_FeatureLanguagesDescription {
            get {
                return ResourceManager.GetString("Home_FeatureLanguagesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy First.
        /// </summary>
        public static string Home_FeaturePrivacyTitle {
            get {
                return ResourceManager.GetString("Home_FeaturePrivacyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All processing happens in your browser. Zero data sent to servers..
        /// </summary>
        public static string Home_FeaturePrivacyDescription {
            get {
                return ResourceManager.GetString("Home_FeaturePrivacyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; Efficient.
        /// </summary>
        public static string Home_FeatureWasmTitle {
            get {
                return ResourceManager.GetString("Home_FeatureWasmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Powered by WebAssembly for native-like performance..
        /// </summary>
        public static string Home_FeatureWasmDescription {
            get {
                return ResourceManager.GetString("Home_FeatureWasmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy-first tools for developers. All processing happens in your browser..
        /// </summary>
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Nav_Tools {
            get {
                return ResourceManager.GetString("Nav_Tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL Encoder.
        /// </summary>
        public static string Nav_UrlEncoder {
            get {
                return ResourceManager.GetString("Nav_UrlEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string Theme_Toggle {
            get {
                return ResourceManager.GetString("Theme_Toggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string UrlEncoder_ActionEncode {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string UrlEncoder_ActionClear {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string UrlEncoder_ActionDecode {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionDecode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string UrlEncoder_ActionSwap {
            get {
                return ResourceManager.GetString("UrlEncoder_ActionSwap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text charset.
        /// </summary>
        public static string UrlEncoder_CharsetLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_CharsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string UrlEncoder_Copied {
            get {
                return ResourceManager.GetString("UrlEncoder_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string UrlEncoder_Copy {
            get {
                return ResourceManager.GetString("UrlEncoder_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode and decode URL-encoded text (percent-encoding) with selectable modes and charsets — all in your browser.
        /// </summary>
        public static string UrlEncoder_Description {
            get {
                return ResourceManager.GetString("UrlEncoder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string UrlEncoder_InputLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_InputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text or URL-encoded string....
        /// </summary>
        public static string UrlEncoder_InputPlaceholder {
            get {
                return ResourceManager.GetString("UrlEncoder_InputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base32.
        /// </summary>
        public static string UrlEncoder_LinkBase32 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base58.
        /// </summary>
        public static string UrlEncoder_LinkBase58 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase58", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string UrlEncoder_LinkBase64 {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string UrlEncoder_LinkHex {
            get {
                return ResourceManager.GetString("UrlEncoder_LinkHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string UrlEncoder_ModeLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_ModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Component (encodeURIComponent-like).
        /// </summary>
        public static string UrlEncoder_Mode_Component {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Component", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Form (application/x-www-form-urlencoded).
        /// </summary>
        public static string UrlEncoder_Mode_Form {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URI (encodeURI-like).
        /// </summary>
        public static string UrlEncoder_Mode_Uri {
            get {
                return ResourceManager.GetString("UrlEncoder_Mode_Uri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other formats:.
        /// </summary>
        public static string UrlEncoder_OtherFormats {
            get {
                return ResourceManager.GetString("UrlEncoder_OtherFormats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string UrlEncoder_OutputLabel {
            get {
                return ResourceManager.GetString("UrlEncoder_OutputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL Encoder / Decoder.
        /// </summary>
        public static string UrlEncoder_Title {
            get {
                return ResourceManager.GetString("UrlEncoder_Title", resourceCulture);
            }
        }
    }
}
